name: Izabela Zelek
title: Izabela Zelek
description: Jekflix is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /let-me-introduce-myself
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: izabelawzelek@gmail.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: mwkznpzp
